### ISSUE TITLE
Hi 👋!

### ISSUE THREAD

**Issue by daveaglick** [aws/codelyzer#26]
Hey there - maintainer of Buildalyzer here. This project was pointed out by a Buildalyzer user and I thought it was really cool. Glad to see the tool being put to use. I'm also pretty curious about where Codelyzer (cool name :smile:) is being used (if you can say)?

In any case, don't be a stranger - happy to fix and issues upstream if you find any.

**Comment by marknfawaz** [comment]
Hi Dave,

Thank you for reaching out, and for writing a great tool! We're using codelyzer to generate a code analysis to be used in other open source projects. Below are these projects. Please do check them out if you get a chance:

Porting assistant client that helps users analyze their .net dependencies and check compatibility with .net core:
https://github.com/aws/porting-assistant-dotnet-client

And

Code translation feature that allows users to automatically port some code from .net framework to .net core:
https://github.com/aws/cta

If you have any questions. comments, suggestions, or if you find anything that needs to be improved please don't hesitate to reach out.

**Comment by daveaglick** [comment]
Cool, thanks! Always fun to learn where your projects are being used.
